services:
  findband_frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    image: ghcr.io/dssorokin/findband/findband_frontend:latest
    ports:
      - 80:80
    links:
      - findband-web
  findband-web:
    build:
      context: backend
      dockerfile: ${PATH_DOCKERFILE}
    container_name: findband_web
    image: ghcr.io/dssorokin/findband/findband_web:latest
    ports:
#      - Use it only for debugging purposes
#      - 5005:5005
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}
      - DB=${DB}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - STORAGE_FOLDER=${STORAGE_FOLDER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    links:
      - findband_redis
      - findband_db
    volumes:
      - storage-data:${STORAGE_FOLDER}
  findband_redis:
    build: backend/docker-redis
    image: ghcr.io/dssorokin/findband/findband_redis:latest
    container_name: findband_redis
    hostname: findband_redis
    ports:
      - 6379:6379
  findband_db:
    image: 'postgres:13.1-alpine'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: findband_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
volumes:
  postgres-data:
  storage-data: