services:
  web:
    build: .
    container_name: findband
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
  findband_db:
    image: 'postgres:13.1-alpine'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: db
    #    ports:
    #    - 5432:5432
    environment:
      - POSTGRES_DB=debts
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
volumes:
  postgres-data: