services:
  findband_web:
    build:
      context: .
      dockerfile: .
    container_name: findband_web
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    links:
      - findband_redis
      - findband_db
  findband_redis:
    build: ./docker-redis
    container_name: findband_redis
    hostname: findband_redis
    ports:
      - 6379:6379
  findband_db:
    image: 'postgres:13.1-alpine'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: findband_db
    environment:
      - POSTGRES_DB=findband
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
volumes:
  postgres-data: