services:
  findband_web:
    build:
      context: .
      dockerfile: ${PATH_DOCKERFILE}
    container_name: findband_web
    image: ghcr.io/dssorokin/findband_web:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}
      - DB=${DB}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - STORAGE_FOLDER=${STORAGE_FOLDER}
    links:
      - findband_redis
      - findband_db
    volumes:
      - storage-data:${STORAGE_FOLDER}
  findband_redis:
    build: ./docker-redis
    image: ghcr.io/dssorokin/findband_web:latest
    container_name: findband_redis
    hostname: findband_redis
    ports:
      - 6379:6379
  findband_db:
    image: 'postgres:13.1-alpine'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: findband_db
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
volumes:
  postgres-data:
  storage-data: